openapi: 3.0.0

info: 
  title: T-Shirt store API
  description: API documentation for T-Shirt store are available here
  version: 0.0.1
  contact:
    email: ridoydeveloper@gmail.com
    url: "ridoydeveloper.netlify.com"

servers: 
  - url: "{protocol}://localhost:3000/api/{version}"
    description: for local host
    variables: 
      version:
        enum:
          - v1
          - v2
        default: v1
      protocol:
        enum:
          - http
          - https
        default: http

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: token
    BearerAuth:
      type: http
      scheme: bearer
